fix occasional type error occurring during some KAT torrent searches
seems specific to just certain episodes that are presumably missing
magnet information on KAT
TypeError: Cannot read property 'match' of null
angular.js:12330
at parseSearch (GenericTorrentSearchEngine.js:95)
at GenericTorrentSearchEngine.js:118
at processQueue (angular.js:14567)
at angular.js:14583
at Scope.$get.Scope.$eval (angular.js:15846)
at Scope.$get.Scope.$digest (angular.js:15657)
at Scope.$get.Scope.$apply (angular.js:15951)
at done (angular.js:10364)
at completeRequest (app.authHttpBackend.js:149)
at XMLHttpRequest.requestLoaded (app.authHttpBackend.js:93)
(anonymous function) @ angular.js:12330
$get @ angular.js:9109
processQueue @ angular.js:14575
(anonymous function) @ angular.js:14583
$get.Scope.$eval @ angular.js:15846
$get.Scope.$digest @ angular.js:15657
$get.Scope.$apply @ angular.js:15951
done @ angular.js:10364
completeRequest @ app.authHttpBackend.js:149
requestLoaded @ app.authHttpBackend.js:93