fix for 972c5248 which caused "TypeError: undefined is not a function
    at chrome-extension://cdfkaloficjmdjbgmckaddgfcghgidei/js/directives/calendar.js:152:41"