prevent typeerror cancelActiveRequest in not a function
when switching to/from rarbg and showrss amoung the others.
full error:
TypeError: TorrentSearchEngines.getSearchEngine(...).cancelActiveRequest
is not a function at Scope.$scope.setProvider (torrentDialog.js:223)